version: '3'
services: 
   db:
     image: mysql:8.0
     container_name: mysql_container
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: yash
         MYSQL_DATABASE: wordpress
         MYSQL_USER: yash
         MYSQL_PASSWORD: wordpress
     volumes:
         - mysql_data:/var/lib/mysql
     networks:
         - wordpress_network
     ports:
         - "3709:3709"
   
   
   wordpress:
     depends_on:
         - db
     image: wordpress:latest
     container_name: wordpress-container
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: yash
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - wordpress_data:/var/www/html
     ports:
       - "6060:80"
     networks:
       - wordpress_network

volumes:
     mysql_data:
     wordpress_data:

networks:
     wordpress_network:
       driver: bridge
     
