#docker-compose.yml

version: '3'
services:
    python_service:
          build:
            context: .
            dockerfile: dockerfile.python
            args:
               - BASE_IMAGE=python:latest
               - APP_VERSION=1.0
          environment:
             - DEBUG=True
          image: yashpatil23/python_web:1.0

    node_service:
           build:
             context: .
             dockerfile: dockerfile.node
             args:
                - BASE_IMAGE=node:latest
                - APP_NAME=my-nodejs-app
           environment:
               - NODE_ENV=development
           image: yashpatil23/node_web:1.0
