FROM nginx:latest

LABEL version="0.0.1"
LABEL maintainer="yashppatilk23@gmail.com"

# Updating the work directory

WORKDIR /usr/share/nginx/html

# Replace the Index.html file with custom file

COPY index.html index.html

